# Travis CI script
# Checks zlabs against libsodium/ZeroMQ/CZMQ master

language: c

before_script:

- sudo apt-get install uuid-dev
- ./autogen.sh

script:

# Perform regression test build against CZMQ master + ZeroMQ master + libsodium
- git clone git://github.com/jedisct1/libsodium.git
- ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
- git clone git://github.com/zeromq/libzmq.git
- ( cd libzmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
- git clone git://github.com/zeromq/czmq.git
- ( cd czmq; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )
- ./configure && make check
- echo "*** zlabs OK against libsodium/libzmq/czmq master"
